export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";
export const GET_MESSAGE = "GET_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const MESSAGE_FAIL = "MESSAGE_FAIL";
